pipeline {
    agent any
    stages{
        stage('Checkout') {
            steps {
                git credentialsId: '3f2aa6eb-6889-4ab1-9ab9-e15f25f9e0da', url: 'https://github.com/HectorRPC/testing-microservices', branch: 'micro1'
                dir('micro1') {
                    echo 'Checkout successfully'
                }
            }
        }
        stage('Restore Packages') {
            steps {
                sh "dotnet restore"
            }
        }
        stage('Clean') {
            steps {
                sh "dotnet clean"
            }
        }
    }
}
