source 'https://rubygems.org'

gem 'jekyll'
gem "github-pages", group: :jekyll_plugins
gem "jekyll-github-metadata"

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
  end